server:
  port: 8082

product:
  service:
    url : http://localhost:8081/api/v1/product
spring:
  application:
    name: microservice-order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-product-order
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

